//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palabra
    {
        public int IdPalabra { get; set; }
        public string Palabra_ { get; set; }
        public string Traduccion { get; set; }
        public string Observacion { get; set; }
        public int IdCapitulo { get; set; }
    }
}
